# Generated by Django 4.2 on 2025-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт')),
                ('employment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Занятость')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'История поисковых запросов',
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True, verbose_name='ID вакансии на HH')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('area', models.CharField(max_length=100, verbose_name='Регион')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('salary_gross', models.BooleanField(null=True, verbose_name='Зарплата до вычета налогов')),
                ('employer_name', models.CharField(max_length=255, verbose_name='Название работодателя')),
                ('employer_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на работодателя')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('experience', models.CharField(max_length=100, verbose_name='Требуемый опыт')),
                ('employment', models.CharField(max_length=100, verbose_name='Тип занятости')),
                ('schedule', models.CharField(max_length=100, verbose_name='График работы')),
                ('alternate_url', models.URLField(verbose_name='Ссылка на вакансию на HH')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('response_count', models.IntegerField(default=0, verbose_name='Количество откликов')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
