# Generated by Django 4.2 on 2025-12-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='response_count',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_gross',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='employment',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='alternate_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на вакансию на HH'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='area',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=10, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='Требуемый опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='key_skills',
            field=models.TextField(blank=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, verbose_name='График работы'),
        ),
    ]
